name: Publish Packages to npmjs
on:
  push:
    branches:
      - main
    paths:
      - "addon/**/*"
      - "framework/**/*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - name: Setup and publish package
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
